### ISSUE TITLE
Add extension to final&reduced Fiber-MOS RSS frames (low priority)

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#135]
The idea is to add another extension with the spectrum of each minibundle by adding the seven individual fibers of each. It seems that adding this as an extension to the final and reduced Fiber-MOS RSS frames would be best.

**Comment by sergiopasra** [comment]
Fixed in d4ea0027ec01f50aa79de9807ca4716ae941a69
