### ISSUE TITLE
In ModelMap, fix divisions by zero

### ISSUE THREAD

**Issue by sergiopasra** [guaix-ucm/megaradrp#149]
/home/spr/devel/guaix/megaraenv/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-linux-x86_64.egg/numina/modeling/gaussbox.py:36: RuntimeWarning: divide by zero encountered in true_divide
  z = (x - mean) / stddev
/home/spr/devel/guaix/megaraenv/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-linux-x86_64.egg/numina/modeling/gaussbox.py:36: RuntimeWarning: invalid value encountered in true_divide
  z = (x - mean) / stddev
/home/spr/devel/guaix/megaraenv/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-linux-x86_64.egg/numina/modeling/gaussbox.py:37: RuntimeWarning: divide by zero encountered in true_divide
  z2 = z + hpix / stddev
/home/spr/devel/guaix/megaraenv/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-linux-x86_64.egg/numina/modeling/gaussbox.py:37: RuntimeWarning: invalid value encountered in add
  z2 = z + hpix / stddev
/home/spr/devel/guaix/megaraenv/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-linux-x86_64.egg/numina/modeling/gaussbox.py:38: RuntimeWarning: divide by zero encountered in true_divide
  z1 = z - hpix / stddev
/home/spr/devel/guaix/megaraenv/lib/python2.7/site-packages/numina-0.15.dev5-py2.7-linux-x86_64.egg/numina/modeling/gaussbox.py:38: RuntimeWarning: invalid value encountered in subtract
  z1 = z - hpix / stddev
/usr/lib64/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/usr/lib64/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/usr/lib64/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:1735: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0

**Comment by gildepaz** [comment]
Same as #163. Closed.
