### ISSUE TITLE
Create median row image (not trimmed)

### ISSUE THREAD

**Issue by acasmor** [guaix-ucm/megaradrp#170]
For a more accurate cosmic ray removing it would be desirable to have the row image create when the three row images of our target is combined. Now we have the reduced.fits which it is trimmed and I do not remember if bias subtracted. 
We would like to have the median image not trimmed and not bias subtracted with the aim to use the cleanest programm to improve on that image the cosmic rays elimination.

**Comment by sergiopasra** [comment]
Now you can run

python -m megaradrp.processing.combine image1.fits image2.fits 

to combine images without any reduction.

check 
python -m megaradrp.processing.combine -h

for options
