### ISSUE TITLE
Tracing problems for the last box

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#175]
A few times already the TraceMap recipe skips fiber 603 assuming that a fiber is missing in between the last two boxes. As a consequence of this, the last fiber (at the very top) is wrongly identified as #623 instead of as fiber #622. The images for which the tracing gives this error are including in the following .yaml file:

id: 4_TraceMap
mode: MegaraTraceMap
instrument: MEGARA
frames:
 - 0001288578-20170802-MEGARA-MegaraSuccess.fits
 - 0001288579-20170802-MEGARA-MegaraSuccess.fits
 - 0001288580-20170802-MEGARA-MegaraSuccess.fits

**Comment by sergiopasra** [comment]
The key here is in this log message

megaradrp.recipes.calibration.trace DEBUG pseudoslit box: 8a, id: 16, npeaks: 20
megaradrp.recipes.calibration.trace DEBUG matched 20 	 missing: 1
megaradrp.recipes.calibration.trace DEBUG we have to pair 1 missing fibers
megaradrp.recipes.calibration.trace DEBUG peaks: 3805.63139689 	 3921.25862133
megaradrp.recipes.calibration.trace DEBUG borders: 3797 	 3929
megaradrp.recipes.calibration.trace DEBUG L distance 8.63139689075 	 0.503955518843
megaradrp.recipes.calibration.trace DEBUG R distance 7.74137866933 	 0.348876586323
megaradrp.recipes.calibration.trace DEBUG add 0 fibers on the right
megaradrp.recipes.calibration.trace DEBUG add 1 fibers on the left

So in box 8a there are 20 peaks, 1 is missing, remaining space on the left is larger, so its assumes
that the missing fiber is there, therefore the wrong assignation
