### ISSUE TITLE
When model map is available, is the extraction_offset parameter relative to the master_traces or to the model_map?

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#191]

**Comment by gildepaz** [comment]
I mean when this parameter is used in either LcbImage or LcbAcquisition or similar

**Comment by acasmor** [comment]
I´m considering the extraction_offset relative to the model_map traces. I use the file ds9_raw.reg generated in the model_map_work subdirectory to see this offset.

**Comment by sergiopasra** [comment]
You mean, in the recipes that allow both types of calibrations as inputs? If this is the case, the extraction_offset is applied to the calibration that is found and passed to the recipe.

**Comment by gildepaz** [comment]
Yes, got it. TraceMap centroids are ignored if ModelMap is available. Thx!
