### ISSUE TITLE
Check minimum number of smoothing window

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#192]
Minimum value for the smoothing_window parameter of Fiberflat recipe (when needed in non-spline format) is 5. When .yaml is processed it should be checked that this value is odd and 5 or larger.

**Comment by sergiopasra** [comment]
After this commit https://github.com/guaix-ucm/numina/commit/cddce749c7d479e443ae4b56fa604fcfa773ba72 values in Parameters (numbers, strings, etc) can have custom validators
