### ISSUE TITLE
New branch should be generated to improve WCS solution in FIbers extension

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#195]

**Comment by sergiopasra** [comment]
We should get the equations right!

**Comment by sergiopasra** [comment]
I'm using the following:

insAngle = -163.256
pa = -insAngle + ipa

And PA is measured from the North to the East

**Comment by sergiopasra** [comment]
With c1480846133df448fb9f3421608f7a4b14e9509d the PA angle and the PC matrix can be computed from IPA: I consider this fixed.
