### ISSUE TITLE
Twilight recipe fails

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#196]
I just updated megaradrp and I tried to run the twilight recipe either using the new normalize_region parameter or without it and it fails in both cases giving the following error:
TypeError: __init__() got an unexpected keyword argument 'validator'

**Comment by sergiopasra** [comment]
Coding too fast. Sorry

**Comment by sergiopasra** [comment]
Ah, you have to update numina also

**Comment by gildepaz** [comment]
Working fine. Sorry & Thx!
