### ISSUE TITLE
Make the conservation of flux in cube optional

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#198]
When using visualization.py to create contours, the level of the pseudo-cube created to generate the contours assumes it has to conserve "flux" but when it is a data-products RSS such as velocity or sigma (h3, h4, as well) it should conserve "surface brightness" instead. 

Besides, the alignment of the contours and the images is not always perfect.

**Comment by sergiopasra** [comment]
Well, this is not a bug. We are using the function for something it wasn't meant to do. I can make the normalization in cube optional
