### ISSUE TITLE
Problem with numina 17

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#205]
MEGARADRP fails using numina 17 in linux. Going back to numina 16 fix the problem.

**Comment by sergiopasra** [comment]
Numina 0.17 is under development, so it breaks sometimes. Now that the pipeline is mostly stable and well behaved, people should be using stable versions, not development versions.
I'm working to add megaradrp to pypi, so it can be installed with:

`
pip install megaradrp
`

**Comment by sergiopasra** [comment]
Now that the latest megaradrp is in PyPI, I close this issue
