### ISSUE TITLE
LcbStdStar ignores ignored_sky_bundles

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#237]
LcbStdStar ignores ignored_sky_bundles although it reads well the .yaml file requirement. It seems that it needs a change in the /site-packages/megaradrp/recipes/calibration/lcbstdstar.py code.

**Comment by sergiopasra** [comment]
I fixed this in the acquisition recipes but I didn't in the std star recipes. This bug can explain small discrepancies in flux calibration, as the sensitivity is computed with all the sky bundles, regardless of being ignored.
