### ISSUE TITLE
Update alignment angle

### ISSUE THREAD

**Issue by sergiopasra** [guaix-ucm/megaradrp#245]
The alignment angle is defined only in the default argument of a function. Not the best place

https://github.com/sergiopasra/megaradrp-cube/issues/3

@gildepaz

**Comment by gildepaz** [comment]
Could this be part of the model instead? Another option is that is a parameter that is associated with the instrument profile (currently ca3558e3-e50d-4bbc-86bd-da50a0998a48), because it could change if the rotator or the instrument has to be removed from the focus and put it back.

**Comment by sergiopasra** [comment]
I'm writing this as a constant for the moment. I agree that it should go in some component of the instrument profile. I'm working on instrument profiles to make them more versatile
