### ISSUE TITLE
warning for cube.py recipe

### ISSUE THREAD

**Issue by acasmor** [guaix-ucm/megaradrp#252]
When using the cube.py recipe:
python -m megaradrp_cube.cube -p 0.4 final_rss.fits -o test_cube.fits

the following warning shows up:

WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [__main__]

**Comment by sergiopasra** [comment]
Fixed in cube
