### ISSUE TITLE
Master_sensitivity has wrong units

### ISSUE THREAD

**Issue by acasmor** [guaix-ucm/megaradrp#272]
If the parameter "degrade_resolution_method:" is set to "auto" the master_sensitivity.fits has wrong units.

**Comment by sergiopasra** [comment]
In `auto` mode, the code just computes the  `sigma` and then generates the sensitivity with the same code as in `fixed` mode. This means that you should get the same result with `fixed` and `auto` if you use the same `sigma`

**Comment by sergiopasra** [comment]
Well, actually  not true. `compute_broadening` normalizes its inputs, so it should get a copy
