### ISSUE TITLE
insAngle should be changed in both cube and visualization

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megaradrp#282]
The update in the IPA of the MEGARA instrument at GTC from 196.744º (theoretical one based on the telescope configuration at the FC-F focus) and 196.146º (the one computed on sky during commissioning) requires to update the insAngle variable in both the cube.py and visualization.py tools, from -163.256 to -163.854 degrees. Thx!

**Comment by sergiopasra** [comment]
We are actually using -163.854, but only when requested

https://github.com/guaix-ucm/megaradrp/blob/2571f87ceeaf2a3e456fb98c0e99946864c71b0e/megaradrp/instrument/__init__.py#L13
