### ISSUE TITLE
Missmatch between overplot_traces and ds9 load regions

### ISSUE THREAD

**Issue by Vital-Fernandez** [guaix-ucm/megaradrp#305]
Hi, I wonder if anyone could share their input on this issue using the `overplot_traces` script to plot the master_traces.json. 

When I use ds9 to plot the traces from the ds9_raw.reg file I get the expected results:

![ds9_image](https://user-images.githubusercontent.com/4238978/177802239-2ace744f-62f7-4fb8-9e83-a096bd315c12.png)

However, plotting the master_traces.json from the same task I get this:

![megara_drp_image](https://user-images.githubusercontent.com/4238978/177802470-120b4d69-5c44-40e1-8b96-8c09b892ae64.png)

It seems there is an offset in the upper region (and also towards the left in the  spectral direction)

I am using this command:

```
from megaradrp.tools.overplot_traces import main as megaradrp_traces_plot

function_argument_list = [fits_address.as_posix(), master_traces_file.as_posix(), '--fibids']
megaradrp_traces_plot(function_argument_list)
```

I wonder if I am missing some arguments to properly place the traces. 

Thank you very much for any advice.

**Comment by nicocardiel** [comment]
It seems that this image corresponds to a raw frame. In this case you should use the argument '--rawimage'.
Otherwise the code assumes that the image has already been trimmed.

**Comment by Vital-Fernandez** [comment]
Thank you very much that worked perfectly!!
